# Generated by Django 4.0.4 on 2022-04-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
