# Generated by Django 4.0.4 on 2022-04-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclub', '0002_person_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
