# Generated by Django 4.0.4 on 2022-04-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclub', '0003_b_pet_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='B',
        ),
    ]
