# Generated by Django 4.0.4 on 2022-05-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclub', '0005_alter_pet_options_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
